server:
  port: 5001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankingAccount?createDatabaseIfNotExist=true
    username: edwin
    password: Edwin2005$
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-desearilizer: org.apache.kafka.common.serialization.StrinDeserializer
      value-desearilizer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        string:
          json:
            trusted:
              packages: "*"